### ISSUE TITLE
tomcat 

### ISSUE THREAD

**Issue by snailAlice** [ixrjog/opsCloud#1]
请问安装步骤5中，opscloud.war从哪里下载？
“3. 修改opscloud配置文件/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/server.properties”
这个修改的配置内容是什么？文档中写的不是很清楚。

**Comment by ixrjog** [comment]
#源码中已经包含了配置文件，eg:
jdbc_url=jdbc:mysql://10.17.1.20:3306/opscloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true
jdbc_user=opscloud
jdbc_password=opscloud

stash_jdbc_url=jdbc:mysql://10.17.1.20:3306/stash?useUnicode=true&characterEncoding=utf8&autoReconnect=true
stash_jdbc_user=stash
stash_jdbc_password=stash

#ldap配置，建议使用apacheDS,用户dn:cn=user1,ou=users,ou=system
ldapUrl=ldap://10.17.1.152:10389
ldapBase=
# 管理员账户，用户账户管理
ldapUserDn=uid=admin,ou=system
ldapPwd=secret

# 配置文件环境: dev=开发环境，online=线上环境
invoke.env=dev

# //redis配置
redis.host=10.17.1.152
redis.port=6379
# //没有密码可留空
redis.pwd=

# //是否开启定时任务，集群部署使用
task.open=false

# 超级管理员密码
admin.passwd=opscloud

# key临时目录
keystore.filePath=/data/www/keystore/

**Comment by snailAlice** [comment]
代码clone下来后，哪些内容复制到/usr/local/tomcat/webapps/ROOT/ 文件下？

**Comment by ixrjog** [comment]
这是源码需要使用gradle构建，说明文档中有构建命令。构建后会生成opscloud.war此war包解压后放到/usr/local/tomcat/webapps/ROOT/

**Comment by snailAlice** [comment]
ok 谢谢你的解答
