### ISSUE TITLE
编译失败求解

### ISSUE THREAD

**Issue by jianghong213** [ixrjog/opsCloud#15]
![1555583781](https://user-images.githubusercontent.com/26793173/56355463-ec95a000-6208-11e9-90ad-4e71e229e0fe.jpg)

新手，用gradle编译，java版本也是1.8.0_211 。

**Comment by ixrjog** [comment]
看上去是缺少symbol包,代码中用了@Data注解

**Comment by jianghong213** [comment]
Thanks ixrjog, 是我这gradle版本选择错了。
