### ISSUE TITLE
server.properties没有找到

### ISSUE THREAD

**Issue by ns500** [ixrjog/opsCloud#17]
你好，我用最新的代码构建出来的war包，解压之后在WEB-INF/classes/目录里边没有找到配置文件,目录下有com  logback.groovy这些内容。

gradle clean war -DpkgName=opscloud -Denv=online -Dorg.gradle.daemon=false

环境：
Centos7
JDK1.8
Tomcat8.0.36
Gradel3.1

**Comment by ixrjog** [comment]
README里有例子

**Comment by ns500** [comment]
> README里有例子

您的意思是构建之后如果没有这个我配置文件，可以手动创建是吗？

**Comment by ixrjog** [comment]
是的，配置里有私密信息所以没提交

发自我的 iPhone

**Comment by ns500** [comment]
好的，我以为我编译有问题，谢谢。
