### ISSUE TITLE
gradle编译报错

### ISSUE THREAD

**Issue by snailAlice** [ixrjog/opsCloud#2]
执行：
gradle clean war -DpkgName=opscloud -Denv=online -Dorg.gradle.daemon=false
![gradle-error](https://user-images.githubusercontent.com/17794813/48927593-05c44a00-ef12-11e8-803d-aff0128be9c4.png)

error信息：
/data/opsCloud/cmdb-service/src/main/java/com/sdg/cmdb/service/impl/NginxServiceImpl.java:14: error: package com.sun.tools.doclint does not exist
import com.sun.tools.doclint.Env;
                            ^
Note: /data/opsCloud/cmdb-service/src/main/java/com/sdg/cmdb/service/impl/VmServiceImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:cmdb-service:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cmdb-service:compileJava'.
> Compilation failed; see the compiler error output for details.

jdk版本：
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by snailAlice** [comment]
我能暂时去除哪些部分代码或者拉取哪个分支可以完成编译打包工作？

**Comment by ixrjog** [comment]
有几十个类，我下周提交下代码和db你再编译
