### ISSUE TITLE
能把生产服务器的日志，通过opscloud开放给开发工程师自己看吗

### ISSUE THREAD

**Issue by czxin788** [ixrjog/opscloud#31]
就是运维在opscloud上自定义每个生产服务器的日志目录，然后把这些日志通过opscloud，让开发自己在图像界面上看，这样开发自己就能查看生产服务器日志了，不需要运维当二传手了。

类似如下：
![image](https://user-images.githubusercontent.com/13861904/90112362-75cbd100-dd82-11ea-8c5b-f6a5193cdd23.png)

**Comment by ixrjog** [comment]
Aliyun可以用LogService实现你的需求

**Comment by czxin788** [comment]
不是阿里云的，可以实现吗

**Comment by ixrjog** [comment]
ELK或Opscloud中的web终端批量登录服务器查看

**Comment by czxin788** [comment]
web终端批量登录,我感觉就相当于xshell里面多窗口批量执行命令。
但是，这相当于给开发工程师直接开通直连生产服务器的权限了。
我感觉还是不太行，就是想单纯的把linux的日志目录，在opscloud上查看，其他目录一律不给开放。
我感觉这个功能挺实用的，就是没有看到有任何devops项目实现。看来只能自己学学开发，自己搞了，太南了。

**Comment by ixrjog** [comment]
ELK是很成熟的集中日志解决方案没必要重复造轮子，opscloud支持低权限/高权限登录服务器，研发只需申请低权限即可

**Comment by czxin788** [comment]
找到了，程序员看日志的利器，http://www.finderweb.net/，很好
