### ISSUE TITLE
登录提示网关错误

### ISSUE THREAD

**Issue by eagleye1115** [ixrjog/opscloud#33]
部署好以后,登录一直提示网关错误  502
![image](https://user-images.githubusercontent.com/11611725/98060905-b751b100-1e85-11eb-9b1e-76caeedd9209.png)
![image](https://user-images.githubusercontent.com/11611725/98060925-c59fcd00-1e85-11eb-95c1-6a958172f9d8.png)

**Comment by ixrjog** [comment]
请检查：
1. opscloud服务是否启动正常
2. nginx是否配置正确
