### ISSUE TITLE
ApacheDS默认用户admin无法登录

### ISSUE THREAD

**Issue by gaoyuke** [ixrjog/opsCloud#6]
按照配置配好ApacheDS后用admin secret无法登录，提示"登录凭证错误!"

**Comment by ixrjog** [comment]
admin/secret 是LDAP的管理账户，并不能登录opscloud !
默认的管理员是admin/密码在 server.properties/admin.passwd=xxx
新用户可以在opscloud用户管理中创建

**Comment by ixrjog** [comment]
server.properties
# 管理员密码为空，则走ldap认证，DN:cn=admin,ou=users,ou=system(此DN为模版中默认，如果修改了则按配置)
admin.passwd=

**Comment by gaoyuke** [comment]
> server.properties
> 
> ```
> # 管理员密码为空，则走ldap认证，DN:cn=admin,ou=users,ou=system(此DN为模版中默认，如果修改了则按配置)
> admin.passwd=
> ```

**Comment by gaoyuke** [comment]
我当时配了admin.passwd但是还是走到了ldap，提示内部错误

**Comment by gaoyuke** [comment]
![image](https://user-images.githubusercontent.com/31268133/54504052-f22f6a00-496c-11e9-856f-5840f927346b.png)

**Comment by ixrjog** [comment]
把# 去掉，否则配置不生效
我看了下源码，
先走ldap认证,如果认证失败则判断是否为admin,然后比对配置文件中的密码

**Comment by gaoyuke** [comment]
那个#注释掉的在下面有 按说应该生效 现在遇到个奇葩问题 我的tomcat日志不打印日志了= = 我把logs下的日志给删了 重新生成的日志文件不记录你的error日志了

**Comment by ixrjog** [comment]
先用内置账户admin登录（密码可以配置成opscloud）
登录后在用户管理中创建个人账户（此账户会同步到ldap）,然后在 “权限管理”-“用户管理“给自己添加admin角色，最后退出admin用个人账户登录系统

**Comment by gaoyuke** [comment]
关键是现在用admin/opscloud登录不上去 opscloud是配的admin.passwd

**Comment by ixrjog** [comment]
有详细日志么？
或把ldap相关配置留空（你安装的是apacheDS？），重启tomcat再尝试登录

**Comment by gaoyuke** [comment]
是用的apacheDS 如果不想用ldap做登录验证的话是需要把ldap相关配置留空 而不是注释掉吗？

**Comment by ixrjog** [comment]
对只能留空不能注释

**Comment by gaoyuke** [comment]
![image](https://user-images.githubusercontent.com/31268133/54504885-9a92fd80-4970-11e9-910e-97e246d4d042.png)
![image](https://user-images.githubusercontent.com/31268133/54504975-eb0a5b00-4970-11e9-9b54-40ce86275620.png)

**Comment by ixrjog** [comment]
ldap配置要留着，可以是错误的配置

**Comment by gaoyuke** [comment]
所有的ldap前缀配置都要保留 而不是留空吗

**Comment by ixrjog** [comment]
是的，你可以用模版的配置或你修改后的，反正认证失败就会走本地认证。
如有需要可以进QQ群:630913972提问

**Comment by gaoyuke** [comment]
ldap配置走不通也没有走普通认证 现在我给了一个错误的ldap admin的密码 现在提示
![image](https://user-images.githubusercontent.com/31268133/54505646-ae8c2e80-4973-11e9-8d62-4c4da0ed66c2.png) 当你走到哪一步才会去验证admin.passwd呢
